name: Collect Curseforge Rank

on:
  schedule:
  - cron:  "0 0 * * *"
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Install
      run: |
        npm ci
    - name: curseforge:rank
      run: |
        npm run curseforge:rank
    - name: Install Uploader
      run: |
        wget https://raw.githubusercontent.com/MoeClub/OneList/master/OneDriveUploader/amd64/linux/OneDriveUploader -q -O uploader
        chmod 777 ./uploader
    - name: Save Token
      run: 'echo "$TOKEN" > auth.json'
      shell: bash
      env:
        TOKEN: ${{secrets.PAN_AUTH}}
    - name: Upload
      run: |
        ./uploader -s ./web-collect -t 100 -r Data/GitHub -b 20
        time=$(date +"%Y%m%d")
        curl "https://api.jihuayu.site/import/rank?token=$TOKEN&file=$time.json"
      env:
        TOKEN: ${{secrets.API_TOKEN}}
